### ISSUE TITLE
Querying current playback info causes app crash

### ISSUE THREAD

**Issue by maniac103** [sreichholf/dreamDroid#128]
As per the title, querying the information about the current station/recording (via navigation drawer -> "Aktuelle Sendung" -> touch current playback) causes an app crash:

```
04-26 19:44:41.581 I/MainActivity(12208): Fragment CurrentServiceFragment not added, adding
04-26 19:44:41.684 E/SimpleHttpClient(12208): 
04-26 19:44:42.424 D/AndroidRuntime(12208): Shutting down VM
04-26 19:44:42.425 E/AndroidRuntime(12208): FATAL EXCEPTION: main
04-26 19:44:42.425 E/AndroidRuntime(12208): Process: net.reichholf.dreamdroid, PID: 12208
04-26 19:44:42.425 E/AndroidRuntime(12208): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String net.reichholf.dreamdroid.helpers.ExtendedHashMap.getString(java.lang.String)' on a null object reference
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at net.reichholf.dreamdroid.fragment.dialogs.EpgDetailBottomSheet.onCreateDialog(EpgDetailBottomSheet.java:72)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:330)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1308)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at android.os.Handler.handleCallback(Handler.java:873)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at android.os.Looper.loop(Looper.java:193)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at java.lang.reflect.Method.invoke(Native Method)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-26 19:44:42.425 E/AndroidRuntime(12208): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-26 19:44:42.429 W/ActivityManager(1152):   Force finishing activity net.reichholf.dreamdroid/.activities.MainActivity
```

This is with latest release 1.4.434, in previous releases touching the playback didn't do anything, which wasn't exactly better either ;-)

**Comment by maniac103** [comment]
Comparing https://github.com/sreichholf/dreamDroid/blob/master/app/src/net/reichholf/dreamdroid/fragment/CurrentServiceFragment.java#L169 with the factory method, it looks like the bundle key name is off.

**Comment by sreichholf** [comment]
Closing: likely fixed on the 2.0 rewrite (main).
