### ISSUE TITLE
FATAL EXCEPTION: main when tap on an app via share button at the screenshot-activity

### ISSUE THREAD

**Issue by dev-aphex** [sreichholf/dreamDroid#91]
on android 7.1.1
```
02-28 09:57:42.318  8885  8885 D AndroidRuntime: Shutting down VM
02-28 09:57:42.327  8885  8885 E AndroidRuntime: FATAL EXCEPTION: main
02-28 09:57:42.327  8885  8885 E AndroidRuntime: Process: net.reichholf.dreamdroid, PID: 8885
02-28 09:57:42.327  8885  8885 E AndroidRuntime: android.os.FileUriExposedException: file:///data/user/0/net.reichholf.dreamdroid/cache/screenshot.png exposed beyond app through ClipData.Item.getUri()
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.net.Uri.checkFileUriExposed(Uri.java:2346)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:845)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:8957)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:8942)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4225)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4183)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4522)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4490)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.support.v7.widget.ActivityChooserView$Callbacks.onClick(ActivityChooserView.java:607)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.view.View.performClick(View.java:5637)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:22433)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6126)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-28 09:57:42.327  8885  8885 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-28 09:57:42.335   814  1501 W ActivityManager:   Force finishing activity net.reichholf.dreamdroid/.activities.MainActivity
02-28 09:57:42.430   814  4642 I OpenGLRenderer: Initialized EGL, version 1.4
02-28 09:57:42.430   814  4642 D OpenGLRenderer: Swap behavior 1
02-28 09:57:42.771   242   427 I ThermalEngine: Sensor:batt_therm:31100 mC
02-28 09:57:42.845   814   926 W ActivityManager: Activity pause timeout for ActivityRecord{ed12ab6 u0 net.reichholf.dreamdroid/.activities.MainActivity t1290 f}
02-28 09:57:42.958  1982  2162 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (Ia6c73e7530)
```

**Comment by sreichholf** [comment]
I already have a fix for that available

**Comment by sreichholf** [comment]
Closing: likely fixed on the 2.0 rewrite (main).
